name: Lint
on: [ push, pull_request ]

jobs:
  grumphp:
    name: Run GrumPHP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.composer
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Installing PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 8.0
          extensions: mbstring, xdebug, fileinfo, redis, gd, zip, bcmath

      - name: Install Composer dependencies
        run: |
          composer install --no-progress --prefer-dist
      - name: Run GrumPHP
        run: ./vendor/bin/grumphp run