name: Lint
on: [ pull_request ]

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Install
        run: composer install

      - name: Run PHP-CS-Fixer
        run: composer cs-fix